// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import Link from "next/link";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import $$Image from "next/image";
import * as ProjectList from "./ProjectList.js";

function Cards(props) {
  return React.createElement("div", undefined, Belt_Array.mapWithIndex(ProjectList.projects, (function (index, project) {
                    return React.createElement("div", {
                                key: String(index)
                              }, React.createElement(Link, {
                                    children: null,
                                    href: project.path,
                                    className: "flex items-center gap-2"
                                  }, React.createElement("div", undefined, project.name), React.createElement($$Image, {
                                        src: "/assets/arrow.svg",
                                        width: 15.0,
                                        height: 15.0
                                      })), React.createElement("section", undefined, project.description), React.createElement($$Image, {
                                    src: project.image,
                                    width: 300.0,
                                    height: 300.0
                                  }), React.createElement("section", {
                                    className: "flex gap-2"
                                  }, React.createElement($$Image, {
                                        src: "/github.svg",
                                        width: 20.0,
                                        height: 20.0
                                      }), React.createElement("div", {
                                        className: "flex gap-2"
                                      }, Belt_Array.mapWithIndex(project.techs, (function (index, tech) {
                                              return React.createElement("div", {
                                                          key: String(index),
                                                          className: "cursor-pointer bg-gray-300 py-1 px-3 text-xs rounded-full "
                                                        }, tech);
                                            })))));
                  })));
}

var make = Cards;

export {
  make ,
}
/* react Not a pure module */
