// Generated by ReScript, PLEASE EDIT WITH CARE
'use client';

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import Link from "next/link";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import $$Image from "next/image";
import * as ProjectList from "./ProjectList.js";
import * as LucideReact from "lucide-react";

function Cards(props) {
  var category = props.category;
  var match = React.useState(function () {
        return 1000;
      });
  var setHover = match[1];
  var hover = match[0];
  var projects = ProjectList.projects.filter(function (x) {
        return x.category === category;
      });
  return React.createElement("div", {
              className: "grid grid-cols-1 gap-4"
            }, Belt_Array.mapWithIndex(projects, (function (index, project) {
                    return React.createElement("div", {
                                key: String(index),
                                className: "flex flex-col my-4 gap-4",
                                onMouseOut: (function (param) {
                                    Curry._1(setHover, (function (param) {
                                            return 1000;
                                          }));
                                  }),
                                onMouseOver: (function (param) {
                                    Curry._1(setHover, (function (param) {
                                            return index;
                                          }));
                                  })
                              }, React.createElement(Link, {
                                    children: null,
                                    href: project.path,
                                    className: "flex justify-start items-center gap-2 " + (
                                      hover === index ? "text-sky-500" : ""
                                    ) + " cursor-pointer"
                                  }, React.createElement("div", {
                                        className: "font-bold"
                                      }, project.name.toUpperCase()), React.createElement(LucideReact.ArrowRight, {
                                        size: 20,
                                        strokeWidth: 1.0,
                                        className: "" + (
                                          hover === index ? "-rotate-45" : ""
                                        ) + " transition-all duration-300 ease-in-out"
                                      })), React.createElement("section", {
                                    className: "text-sm text-gray-500 text-justify"
                                  }, project.description), React.createElement("section", {
                                    className: "rounded-lg bg-black"
                                  }, React.createElement($$Image, {
                                        alt: project.name,
                                        className: "w-full h-auto",
                                        src: project.image,
                                        width: 300.0,
                                        height: 300.0
                                      })), React.createElement("section", {
                                    className: "flex justify-start items-center gap-2"
                                  }, React.createElement(Link, {
                                        children: React.createElement(LucideReact.Github, {
                                              color: "white",
                                              className: "bg-gray-800 rounded-full p-1"
                                            }),
                                        href: project.github
                                      }), React.createElement("div", {
                                        className: "grid grid-cols-5 items-center gap-2"
                                      }, Belt_Array.mapWithIndex(project.techs, (function (index, tech) {
                                              return React.createElement("div", {
                                                          key: String(index),
                                                          className: "flex justify-center items-center bg-sky-200 py-2 px-3 text-xs text-sky-600 rounded-full "
                                                        }, tech);
                                            })))));
                  })));
}

var Link$1;

var $$Image$1;

var make = Cards;

export {
  Link$1 as Link,
  $$Image$1 as $$Image,
  make ,
}
/* react Not a pure module */
