// Generated by ReScript, PLEASE EDIT WITH CARE
'use client';

import * as Cards from "./Cards.js";
import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import Link from "next/link";
import * as LucideReact from "lucide-react";

var title = "PROJECTS";

function Projects(props) {
  var match = React.useState(function () {
        return "fullstack";
      });
  var setCategory = match[1];
  var category = match[0];
  var handleCategory = function (category) {
    if (category === "fullstack") {
      return Curry._1(setCategory, (function (param) {
                    return "frontend";
                  }));
    } else {
      return Curry._1(setCategory, (function (param) {
                    return "fullstack";
                  }));
    }
  };
  return React.createElement("div", {
              className: "flex flex-col gap-4"
            }, React.createElement("section", {
                  className: "font-bold text-gray-700"
                }, title), React.createElement("section", {
                  className: "flex gap-2 my-4"
                }, React.createElement("div", {
                      className: "flex justify-center items-center cursor-pointer " + (
                        category === "fullstack" ? "bg-gray-200" : "hover:bg-gray-200"
                      ) + " py-3 px-5 text-xs rounded-full cursor-pointer transition-all duration-200 easy-in-out",
                      onClick: (function (param) {
                          handleCategory(category);
                        })
                    }, "Fullstack"), React.createElement("div", {
                      className: "flex justify-center items-center cursor-pointer py-3 px-5 text-xs " + (
                        category === "frontend" ? "bg-gray-200" : "hover:bg-gray-200"
                      ) + " rounded-full cursor-pointer transition-all duration-200 easy-in-out",
                      onClick: (function (param) {
                          handleCategory(category);
                        })
                    }, "Frontend")), React.createElement(Cards.make, {
                  category: category
                }), React.createElement(Link, {
                  children: null,
                  href: "/archive",
                  className: "flex justify-start items-center gap-1 hover:gap-2 mb-24 hover:underline transition-all duration-200 ease-in-out cursor-pointer"
                }, React.createElement("div", {
                      className: "font-bold text-xs"
                    }, "Explore all projects"), React.createElement(LucideReact.ArrowRight, {
                      size: 16,
                      strokeWidth: 1.0
                    })));
}

var make = Projects;

export {
  title ,
  make ,
}
/* Cards Not a pure module */
