// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Cards from "./Cards.js";
import * as React from "react";

var title = "PROJECTS";

function Projects(props) {
  return React.createElement("div", {
              className: "flex flex-col"
            }, React.createElement("section", {
                  className: "font-bold"
                }, title), React.createElement("section", {
                  className: "flex gap-2 my-4"
                }, React.createElement("div", {
                      className: "cursor-pointer bg-gray-300 py-1 px-3 text-xs rounded-full "
                    }, "Fullstack"), React.createElement("div", {
                      className: "cursor-pointer bg-gray-300 py-1 px-3 text-xs rounded-full "
                    }, "Frontend")), React.createElement(Cards.make, {}));
}

var make = Projects;

export {
  title ,
  make ,
}
/* Cards Not a pure module */
