// Generated by ReScript, PLEASE EDIT WITH CARE


var Github = {};

var Linkedin = {};

var Code2 = {};

var Database = {};

var MonitorDot = {};

var ArrowRight = {};

var ArrowLeft = {};

export {
  Github ,
  Linkedin ,
  Code2 ,
  Database ,
  MonitorDot ,
  ArrowRight ,
  ArrowLeft ,
}
/* No side effect */
