// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Profile from "../components/Profile.js";
import * as Projects from "../components/Projects/Projects.js";

function Main$page(props) {
  return React.createElement("section", {
              className: "grid grid-cols-1 lg:grid-cols-2 gap-36 lg:gap-16 p-8 lg:p-0 max-w-4xl lg:m-auto lg:my-24 h-screen"
            }, React.createElement(Profile.make, {}), React.createElement(Projects.make, {}));
}

var page = Main$page;

export {
  page ,
}
/* react Not a pure module */
