// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Profile from "../components/Profile.js";
import * as Projects from "../components/Projects/Projects.js";

function Main$page(props) {
  return React.createElement("section", {
              className: "flex flex-col p-4 gap-5"
            }, React.createElement(Profile.make, {}), React.createElement(Projects.make, {}));
}

var page = Main$page;

export {
  page ,
}
/* react Not a pure module */
