// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import Link from "next/link";
import * as LucideReact from "lucide-react";

var title = "ABOUT";

var myName = "Kemal Maolana";

var myStatus = "Junior Full Stack Developer";

var description = "I code and design visually captivating full-stack applications that prioritize user experience.";

function Profile(props) {
  return React.createElement("section", undefined, React.createElement("div", {
                  className: "flex flex-col gap-4 lg:sticky lg:top-24"
                }, React.createElement("div", {
                      className: "font-bold text-gray-700"
                    }, title), React.createElement("div", {
                      className: "text-6xl font-bold my-2"
                    }, myName), React.createElement("div", {
                      className: "font-bold text-gray-700"
                    }, myStatus), React.createElement("div", {
                      className: "text-gray-500 text-sm"
                    }, description), React.createElement("section", {
                      className: "flex gap-2 my-2"
                    }, React.createElement(Link, {
                          children: React.createElement(LucideReact.Github, {
                                color: "white",
                                className: "bg-gray-800 rounded-full p-1"
                              }),
                          href: "https://github.com/kemalmao19"
                        }), React.createElement(Link, {
                          children: React.createElement(LucideReact.Linkedin, {
                                color: "white",
                                className: "bg-gray-800 rounded-full p-1"
                              }),
                          href: "https://www.linkedin.com/in/kemal-maolana-yusuf/"
                        })), React.createElement("section", {
                      className: "flex flex-col gap-4"
                    }, React.createElement("div", {
                          className: "flex flex-col gap-2"
                        }, React.createElement("div", {
                              className: "flex gap-2"
                            }, React.createElement(LucideReact.Code2, {
                                  color: "#0284c7",
                                  size: 20,
                                  className: "bg-sky-200 rounded-full p-1"
                                }), React.createElement("p", {
                                  className: "text-sm"
                                }, "Languages")), React.createElement("p", {
                              className: "text-xs text-gray-500"
                            }, "Python • JavaScript • Rescript")), React.createElement("div", {
                          className: "flex flex-col gap-2"
                        }, React.createElement("div", {
                              className: "flex gap-2"
                            }, React.createElement(LucideReact.MonitorDot, {
                                  color: "#0284c7",
                                  size: 20,
                                  className: "bg-sky-200 rounded-full p-1"
                                }), React.createElement("p", {
                                  className: "text-sm"
                                }, "Front End")), React.createElement("p", {
                              className: "text-xs text-gray-500"
                            }, "HTML • CSS/Tailwind • React • Next.js")), React.createElement("div", {
                          className: "flex flex-col gap-2"
                        }, React.createElement("div", {
                              className: "flex gap-2"
                            }, React.createElement(LucideReact.Database, {
                                  color: "#0284c7",
                                  size: 20,
                                  className: "bg-sky-200 rounded-full p-1"
                                }), React.createElement("p", {
                                  className: "text-sm"
                                }, "Back End")), React.createElement("p", {
                              className: "text-xs text-gray-500"
                            }, "Node.js • Flask • PostgreSQL • MySQL • Prisma • Postman")))));
}

var make = Profile;

export {
  title ,
  myName ,
  myStatus ,
  description ,
  make ,
}
/* react Not a pure module */
