// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import Link from "next/link";
import * as LucideReact from "lucide-react";

var title = "ABOUT";

var myName = "Kemal Maolana";

var myStatus = "Jr. Full Stack Developer";

var description = "I code and design visually captivating full-stack applications that prioritize user experience.";

function Profile(props) {
  return React.createElement("div", {
              className: "flex flex-col gap-4"
            }, React.createElement("div", {
                  className: "font-bold"
                }, title), React.createElement("div", {
                  className: "text-4xl font-bold my-4"
                }, myName), React.createElement("div", {
                  className: "font-bold"
                }, myStatus), React.createElement("div", {
                  className: "text-gray-500"
                }, description), React.createElement("div", {
                  className: "flex gap-2"
                }, React.createElement(Link, {
                      children: null,
                      href: "https://github.com/kemalmao19"
                    }, React.createElement(LucideReact.Github, {
                          color: "white",
                          className: "bg-gray-800 rounded-full p-1"
                        }), React.createElement(React.Fragment, undefined)), React.createElement(Link, {
                      children: null,
                      href: "https://www.linkedin.com/in/kemalmao/"
                    }, React.createElement(LucideReact.Linkedin, {
                          color: "white",
                          className: "bg-gray-800 rounded-full p-1"
                        }), React.createElement(React.Fragment, undefined))));
}

var make = Profile;

export {
  title ,
  myName ,
  myStatus ,
  description ,
  make ,
}
/* react Not a pure module */
