// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import Link from "next/link";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as ProjectList from "../Projects/ProjectList.js";
import * as LucideReact from "lucide-react";

function head(param) {
  return React.createElement("thead", undefined, React.createElement("tr", undefined, React.createElement("th", undefined, "Created"), React.createElement("th", undefined, "Name"), React.createElement("th", {
                      className: "hidden lg:table-cell"
                    }, "Technologies"), React.createElement("th", undefined, "")));
}

function body(param) {
  return React.createElement("tbody", undefined, Belt_Array.mapWithIndex(ProjectList.allProject, (function (index, project) {
                    return React.createElement("tr", {
                                key: String(index),
                                className: "border-b"
                              }, React.createElement("td", {
                                    className: "text-sky-500 py-4 lg:py-0"
                                  }, project.created), React.createElement("td", {
                                    className: "py-4 lg:py-0"
                                  }, project.name), React.createElement("td", {
                                    className: "py-4 hidden lg:flex lg:items-center gap-1"
                                  }, Belt_Array.mapWithIndex(project.techs, (function (index, tech) {
                                          return React.createElement("div", {
                                                      key: String(index),
                                                      className: "flex justify-center items-center bg-sky-200 py-2 px-3 text-xs text-sky-600 rounded-full "
                                                    }, tech);
                                        }))), React.createElement("td", {
                                    className: "py-4 lg:py-0"
                                  }, React.createElement(Link, {
                                        children: React.createElement(LucideReact.Github, {
                                              color: "white",
                                              size: 20,
                                              className: "bg-gray-800 rounded-full p-1"
                                            }),
                                        href: project.github
                                      })));
                  })));
}

function projectTable(param) {
  return React.createElement("table", {
              className: "w-full text-xs text-left space-y-4"
            }, head(undefined), body(undefined));
}

function AllProject(props) {
  return React.createElement("div", {
              className: "flex flex-col gap-4 mb-24"
            }, React.createElement("div", {
                  className: "text-4xl font-bold my-2"
                }, "All Projects"), projectTable(undefined));
}

var make = AllProject;

export {
  head ,
  body ,
  projectTable ,
  make ,
}
/* react Not a pure module */
