// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import Link from "next/link";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import $$Image from "next/image";
import * as ProjectList from "../Projects/ProjectList.js";
import * as LucideReact from "lucide-react";

function Journey(props) {
  return React.createElement("div", undefined, React.createElement("div", {
                  className: "text-4xl font-bold my-2"
                }, "Journey"), React.createElement("div", {
                  className: "flex flex-no-wrap overflow-x-scroll items-start my-8 bg-gray-100 p-6 gap-4"
                }, Belt_Array.mapWithIndex(ProjectList.journey, (function (index, project) {
                        return React.createElement("section", {
                                    key: String(index),
                                    className: "flex-none w-2/3 hover:border border border-sky-50 hover:border-sky-400 hover:bg-sky-100 rounded-lg p-2 space-y-4  transition-all duration-200 ease-in-out"
                                  }, React.createElement("div", {
                                        className: "bg-slate-500"
                                      }, React.createElement($$Image, {
                                            alt: project.name,
                                            className: "object-cover w-full h-44",
                                            src: project.image,
                                            width: 200.0,
                                            height: 150.0
                                          })), React.createElement("div", {
                                        className: "space-y-1"
                                      }, React.createElement("div", {
                                            className: "flex items-center justify-between"
                                          }, React.createElement("div", {
                                                className: "flex items-center gap-2 text-sky-500"
                                              }, React.createElement("div", {
                                                    className: "text-xs"
                                                  }, project.created), React.createElement("div", {
                                                    className: "text-xs"
                                                  }, " • "), React.createElement("div", {
                                                    className: "text-xs"
                                                  }, project.apptype)), React.createElement(Link, {
                                                children: React.createElement(LucideReact.Github, {
                                                      color: "white",
                                                      size: 20,
                                                      strokeWidth: 1.0,
                                                      className: "bg-gray-800 rounded-full p-1"
                                                    }),
                                                href: project.github
                                              })), React.createElement("div", {
                                            className: "font-bold"
                                          }, project.name), React.createElement("div", {
                                            className: "text-xs text-gray-600 text-justify"
                                          }, project.description)), React.createElement("div", {
                                        className: "grid grid-cols-3 items-center gap-2"
                                      }, Belt_Array.mapWithIndex(project.techs, (function (index, tech) {
                                              return React.createElement("div", {
                                                          key: String(index),
                                                          className: "flex justify-center items-center bg-sky-200 py-2 px-3 text-xs text-sky-600 rounded-full "
                                                        }, tech);
                                            }))));
                      }))));
}

var make = Journey;

export {
  make ,
}
/* react Not a pure module */
