// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import Link from "next/link";
import * as LucideReact from "lucide-react";

function Adopthunt$page(props) {
  return React.createElement("div", {
              className: "flex flex-col p-8 lg:p-0 max-w-4xl lg:m-auto lg:my-12"
            }, React.createElement(Link, {
                  children: null,
                  href: "/",
                  className: "flex justify-start hover:text-sky-400 items-center gap-1 hover:gap-2 mt-24 transition-all duration-200 ease-in-out cursor-pointer"
                }, React.createElement(LucideReact.ArrowLeft, {
                      size: 20,
                      strokeWidth: 1.0
                    }), React.createElement("div", {
                      className: "font-bold"
                    }, "Kemal Mao")));
}

var page = Adopthunt$page;

export {
  page ,
}
/* react Not a pure module */
